/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SubscriptionsCollectionDocumentApiImplEventExposure.h"

namespace oai {
namespace amf {
namespace api {

using namespace oai::amf::model;

SubscriptionsCollectionDocumentApiImplEventExposure::
    SubscriptionsCollectionDocumentApiImplEventExposure(
        const std::shared_ptr<Pistache::Rest::Router>& rtr,
        amf_application::amf_app* amf_app_inst)
    : SubscriptionsCollectionDocumentApiEventExposure(rtr),
      m_amf_app(amf_app_inst) {}

void SubscriptionsCollectionDocumentApiImplEventExposure::create_subscription(
    const AmfCreateEventSubscription& amfCreateEventSubscription,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace amf
}  // namespace oai
